version: "3"

services:
  app:
    container_name: react-app
    build:
      context: .
      dockerfile: .Dockerfile
    # ports:
    #   - "80:80"

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: "test.yukendev.com -> http://app:80"
      STAGE: "production"
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data:
